### ISSUE TITLE
ElasticSearch down ?

### ISSUE THREAD

**Issue by Vigneshent** [getcandy/api-boilerplate#3]
Elasticsearch down issue while adding product
Checked elastic search is running fine while testing in curl

**Comment by glennjacobs** [comment]
We would need more information than that to help. We are running many instances of GetCandy without issue.

What version of GetCandy, what version of Elasticsearch, how are you adding a product? etc

**Comment by Vigneshent** [comment]
Hi ,am using this potboiler api version and elasticsearch 7.13.2.
Adding product in admin hub and it showing error
While running  localhost:9200, i am getting

{
  "name" : "DESKTOP-0O4LF6P",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "Coz7a_63QjWE8W9L9YgkSg",
  "version" : {
    "number" : "7.13.2",
    "build_flavor" : "unknown",
    "build_type" : "unknown",
    "build_hash" : "4d960a0733be83dd2543ca018aa4ddc42e956800",
    "build_date" : "2021-06-10T21:01:55.251515791Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

**Comment by Vigneshent** [comment]
Also, while running "php artisan candy:products:reindex"

am getiing

  Couldn't connect to host, Elasticsearch down?

  at C:\xampp7\htdocs\api\vendor\ruflin\elastica\src\Transport\Http.php:186

**Comment by Vigneshent** [comment]
For now, am working in my localhost:8000 for API and localhost:3000 fro HUB
Product adding URL from HUB is like
http://localhost:8000/api/v1/products
it returns Elasticsearch down in response [but product added in database, but not retrieving in admin hub]

**Comment by glennjacobs** [comment]
Can you try ES 7.9? I'm not sure what changes have happened since that version.

**Comment by Vigneshent** [comment]
ok sure, i will check now

**Comment by Vigneshent** [comment]
installed and got same issue with 7.9

**Comment by Vigneshent** [comment]
I am seeing this in terminal

C:\xampp7\htdocs\shopping\api>php artisan candy:categories:reindex

 Indexing 5 categories in 1 batches

   Elastica\Exception\Connection\HttpException

  Couldn't connect to host, Elasticsearch down?

  at C:\xampp7\htdocs\shopping\api\vendor\ruflin\elastica\src\Transport\Http.php:186
    182▕             throw new PartialShardFailureException($request, $response);
    183▕         }
    184▕
    185▕         if ($errorNumber > 0) {
  ➜ 186▕             throw new HttpException($errorNumber, $request, $response);
    187▕         }
    188▕
    189▕         return $response;
    190▕     }

  1   C:\xampp7\htdocs\shopping\api\vendor\ruflin\elastica\src\Request.php:181
      Elastica\Transport\Http::exec(Object(Elastica\Request), [])

  2   C:\xampp7\htdocs\shopping\api\vendor\ruflin\elastica\src\Client.php:512
      Elastica\Request::send()

**Comment by glennjacobs** [comment]
Might be a memory issue with Elasticsearch. Are you running it in Docker or something?

**Comment by Vigneshent** [comment]
No, am not using docker or any other tools

**Comment by glennjacobs** [comment]
I would suggest you check the ES logs to see what's happening.

**Comment by Vigneshent** [comment]
Tried and no logs is helpful

[2021-06-16T14:47:59,329][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [DESKTOP-0O4LF6P] adding index lifecycle policy [metrics]
[2021-06-16T14:47:59,532][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [DESKTOP-0O4LF6P] adding index lifecycle policy [watch-history-ilm-policy]
[2021-06-16T14:47:59,704][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [DESKTOP-0O4LF6P] adding index lifecycle policy [ilm-history-ilm-policy]
[2021-06-16T14:47:59,878][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [DESKTOP-0O4LF6P] adding index lifecycle policy [slm-history-ilm-policy]
[2021-06-16T14:48:00,429][INFO ][o.e.l.LicenseService     ] [DESKTOP-0O4LF6P] license [f13725e0-81c1-42c4-a821-f4c41c39a5c7] mode [basic] - valid

**Comment by glennjacobs** [comment]
Hmmm I'm a bit out of ideas. The error is telling us Elasticsearch is down, so it shouldn't be related to the GetCandy code.

**Comment by Vigneshent** [comment]
yes, tried installing many versions of ElasticSearch and still the issue occurs

Do i need to setup host here in config/getcandy.php

 'search' => [
        'client' => \GetCandy\Api\Core\Search\Providers\Elastic\Elastic::class,
        'batch_size' => 1000,
        'client_config' => [
            'elastic' => [
                'host' => '0.0.0.0',
                'port' => null,
                'path' => null,
                'url' => null,
                'proxy' => null,
                'transport' => null,
                'persistent' => true,
                'timeout' => null,
                'connections' => [], // host, port, path, timeout, transport, compression, persistent, timeout, username, password, config -> (curl, headers, url)
                'roundRobin' => false,
                'log' => false,
                'retryOnConflict' => 0,
                'bigintConversion' => false,
                'username' => null,
                'password' => null,
            ],
        ],

**Comment by glennjacobs** [comment]
Yeah, you'll want to set this bit...

```
    'search' => [
        'client' => \GetCandy\Api\Core\Search\Providers\Elastic\Elastic::class,
        'client_config' => [
            'elastic' => [
                'host' => env('SEARCH_HOST', null),
                'port' => env('SEARCH_PORT', null),
            ]
        ],
```

**Comment by Vigneshent** [comment]
Tried and same issue

**Comment by Vigneshent** [comment]
Issue solved by clearing artisan cache. even we have changed getcandy.php config file. cache overrides and shown the same old configuration,once i cleared i got results. Thanks

**Comment by glennjacobs** [comment]
Had to be something silly hey. Suggest you don't cache the config when in development, only production or testing in readiness for production.

**Comment by Vigneshent** [comment]
ok sure thanks for your help
